### ISSUE TITLE
Search free stock photos without leaving wp

### ISSUE THREAD

**Issue by ferrbea** [sirulli/yoimages#3]
Option to search over a specific set of url images with creative commons license to upload both from media library and from post.
e.g. http://search.creativecommons.org/ which has API.
But there are many others to search from:
some are summarised here: http://thestocks.im/ e qui https://medium.com/@dustin/stock-photos-that-dont-suck-62ae4bcbe01b
Others are Tumblr or website with or without a search form.
Search function should be available from media uploader (by filename? by tag or category if provided? or other attributes if provided? by visual similarity with a photo uploaded? )

**Comment by fagia** [comment]
http://graphicriver.net/forums/thread/where-to-find-free-images-/156850

**Comment by fagia** [comment]
http://pixabay.com/ has advanced filters in its API: http://pixabay.com/api/docs/
It requires user registration and it seems to have more images but with lower quality (comparing it with http://www.splashbase.co/)

**Comment by fagia** [comment]
new possible sources:
http://freeimages.pictures/
https://unsplash.com/

**Comment by fagia** [comment]
http://freeimages.pictures/ seems to be dead... :/

**Comment by fagia** [comment]
added support for https://unsplash.com/ (http://freeimages.pictures/ is officially dead)
