### ISSUE TITLE
[Feature] - Support for media regeneration

### ISSUE THREAD

**Issue by robert388** [sirulli/yoimages#33]
Would it be possible to have support for regenerate functionality?

For example when using a regenerate plugin (https://wordpress.org/plugins/regenerate-thumbnails/) or the regenerate fucntion of wp-cli(https://github.com/wp-cli/wp-cli)  after adding a new custom imagesize it will remove all custom "yoimg_attachment_metadata" from the attachment.
Also they will overwrite all custom crops with the default crop. 

So far i couldn't come up with a solution to this problem.

**Comment by ferrbea** [comment]
Hi Robert,
thank you for getting in touch. 

We'll look into it, to see if we can find a solution. 

We'll send you updates here, in that case.

Thank you

Sirulli Team

**Comment by robert388** [comment]
Hi Ferrbea,

Thanks for the update. I really needed this to work so I've been tinkering on it myself.
I just added a pull request on the yoimages-crop repo which works. ( https://github.com/sirulli/yoimages-crop/pull/2 )

I hope to hear from you :)!

Gr,
Robert

**Comment by ryanurban** [comment]
Hi @robert388 & @ferrbea:

Question about this feature. Is something additional required after regenerating images? After I regenerate images, the image size that I custom cropped on the FE is not being displayed, however if I look at the custom image size that I cropped in the edit crop sizes overlay I do see the position that I custom set my crop to in the crop preview: https://cloudup.com/cCjlvTZ2Wi4

**Comment by stefanfisk** [comment]
I am also experiencing the generated thumbnails not retaining the crop rectangle after running Regenerate Thumbnails. The crop metadata is saved, but the file is not cropped accordingly.
