### ISSUE TITLE
Localization improvements // Polish translation

### ISSUE THREAD

**Issue by odie2** [sirulli/yoimages#36]
Hi,
Awesome cropping plugin, no compare with my previous ;)

As every plugin I use **have to** be in my native Polish (most translated by me), this awesome plugin also needs to be localized. As I can see, plugin is already localization ready, but not possible to use use .mo files yet.

When about you going to release version with localization system (and template) ready?
Can I already start translating 73 extracted (with poEdit) phrases from 0.1.1 version or you are going to change a little in phrases before?

Greetings

**Comment by fagia** [comment]
Hi Odie2 thanks for your feedback! We really appreciate it
We're managing translations with poeditor.com: https://poeditor.com/projects/view?id=25799
If you want, you can contribute Polish translations directly there.
Or do you mean to provide translations via https://translate.wordpress.org/ ? If so, as of now, we don't support it but we're thinking about whether to switch to it or not. What do you think about it? Did you have direct experience on translating your plugins with https://translate.wordpress.org/ ?
Cheers,
   Sirulli

**Comment by odie2** [comment]
Hi,
I mean that I can't find any template like like `_template.pot` or `english.po` to start translating.

For manual translations I also use poEditor.
For translation platforms I have mixed impressions:
* https://translate.wordpress.org/ - nice for integrated with newer WP, so users could update translation only (without plugin updates), sucks for that every single phrase have to be reviewed by language team (so this may take much time in some cases),
* https://www.transifex.com/ (by http://wp-translations.org/) - very powerful platform and useful for translators, but last time there was big discussion on in most cases you can't update existing phrase without lossing it translation (in some times it's saved in Translation Memory however).

If I were you I would use Transifex or just manual files, as official WP translation platform is just too young and have some bugs and the most important reason - I personally hate platforms where I have to ask someone to review it - especially in bigger projects it makes done translation have to wait even months! I don't know who invented such stupid idea of translations ._.

Greetings

**Comment by fagia** [comment]
Hi odie2! if you request access to YoImages translations project here: https://poeditor.com/projects/view?id=25799 we add you to the contributors and you can download the updated .po file from there and provide your translations.
Greetings,
   Sirulli

**Comment by odie2** [comment]
Ah, I mismatched POEditor website app with poEdit computer app :P
Anyways, I just requested for Polish language. Thanks.

**Comment by odie2** [comment]
Oh my... There is languages directory, just some deeper in structure :)

Polish translation done.
However, it would be nice to have `%s` keyword in things like `The sizes listed below are the crop and resize formats defined by` (`The sizes listed below are the crop and resize formats defined by %s`), so I could use some ending dots and apostrophes in phrases with name of theme/image size.

What about plugin's description (`Better image handling capabilities for Wordpress: image cropping tools and image SEO with automated metadata filling.`)?
This works as following comment for Hyphenator plugin:
```
Description: Soft hyphens are automatically added in the content for a nicer automatic word wrap. Particularly suitable for justification. Uses <a href="http://code.google.com/p/hyphenator/">Hyphenator.js</a>.
[...]
Text Domain: hyphenator
Domain Path: /languages/
```
I guess you have to set `/vendor/sirulli/yoimages-commons/inc/languages/`.

**Comment by Maikuolan** [comment]
> Hi odie2! if you request access to YoImages translations project here: > https://poeditor.com/projects/view?id=25799 we add you to the contributors and you can download the updated .po file from there and provide your translations.

Hi,

I found your repository by using the GitHub search functionality, and I'm replying in response to the above quoted text.

I've created a repository for a list just now for the purposes of listing GitHub repositories that are also registered with POEditor, that are looking for and/or willing to accept translators, available here -> https://github.com/Maikuolan/GitHub-OS-POEditor-Projects-List

Would you be interested in having your repository listed on this list, and would I have your permission to list it there? Cheers. :-)

PS, if this is a terrible idea, feel free to let me know, or to just ignore my reply to this issue.

**Comment by ferrbea** [comment]
Hi Maikuolan,
sure! We think it's a good idea so, go ahead!

Cheers,
Sirulli team

**Comment by Maikuolan** [comment]
Awesome! Cheers, and added. :-)
