### ISSUE TITLE
Feature request: rename image formats

### ISSUE THREAD

**Issue by Tom2527** [sirulli/yoimages#40]
It would be great if the plugin allows to rename the image formats. My theme has 7 of them and they have quite cryptic names. The plugin Manual Image Crop allows this, but I would like to replace it with this great plugin!

**Comment by fagia** [comment]
Hi @Tom2527 we're working on it...we're updating you as soon as it will be released

**Comment by fagia** [comment]
Hi @Tom2527 the capability to rename image formats have been released, cheers
