### ISSUE TITLE
Add "Search" option to all media related pages

### ISSUE THREAD

**Issue by scottybo** [sirulli/yoimages#43]
Unless I'm mistaken, it seems the "Search" tab only appears on the Featured Image modal window. 

Media management can happen in multiple places within the Wordpress admin and it would be great if YoImages could be integrated more deeply, e.g. when browsing the media library or choosing "Add new" from the media library.

**Comment by fagia** [comment]
Hi @scottybo,
yes, you're right...
Adding the search option to all wp-admin modal boxes is not so straightforward and we think that the use of stock images is mainly meant for placeholder images (which usually are rendered via the posts' featured image).
We don't see much value in using the search of stock images to create galleries or to get other images to be added into the body of an article...
If you see any valid use case please let us know so we can discuss and evaluate it.
Regards,
   Team Sirulli

**Comment by scottybo** [comment]
I use a page builder called cornerstone and inserting an image is done using the standard WordPress media modal. This is a very common approach in WordPress page Builders and these builders are growing in popularity daily. 

I'd love to be able to insert placeholder images via yoimages this WordPress modal

**Comment by fagia** [comment]
Hi @scottybo 
we've just added the image search tab in the "Add Media" popup, please upgrade to the latest version to try the new feature
