### ISSUE TITLE
yoimages-seo doesn't sanitize filename changes.

### ISSUE THREAD

**Issue by oxyc** [sirulli/yoimages#45]
If a post includes invalid characters such as 📸🍂💃🏽, they do not get sanitized.

The fix would be to use the core `wp_unique_filename` function which internally calls `sanitize_file_name` that fixes the issue. This would also solve the suffixed counters without custom code.

**Comment by fagia** [comment]
added `sanitize_file_name` (but no wp_unique_filename since it would have other side effects)
