### ISSUE TITLE
Not working after PHP7 update

### ISSUE THREAD

**Issue by vdberto** [sirulli/yoimages#46]
As soon as I update my server to PHP7 (from PHP 5.6), the plugin stops to work properly.
Everything seems to work… the “edit crop formats” link is there, you can click and its popup shows up… so when you crop something the image is not generated… turns into an image link 404 error.

Seems that it don’t save the JPG in server. Anyone faced it? Knows how to solve it?

**Comment by fagia** [comment]
hi @vdberto could you please specify the exact PHP7 so that we can try to reproduce the same issue?

**Comment by vdberto** [comment]
Guys, I'm trully sorry and ashamed. I forgot to install GD library... so obviously didn't work with PHP7.
I've just installed PHP7-GD and now everything is fine!
thanks and sorry again

**Comment by fagia** [comment]
No problem, thanks for your feedback
